[package]
name = "tree-select-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23"
clap = "3.1"
serde = "1.0"
tui = "0.18"
